/** 
 * @author HJOW <hujinone22@naver.com>
 * @license Apache-2.0 
*/
/* StringTable 모음 */

const SSStringTable = {
    'ko' : {
        'PLAY' : '플레이',
        'SETTING' : '설정',
        'CREDIT' : 'CREDIT',
        'RECORDS' : '기록',
        'LISTEN' : '감상',
        'MOVE : ' : '이동 : ',
        'ACCEPT : ' : '확인 : ',
        'ACCEPT' : '확인',
        'Accept' : '확인',
        'CANCEL' : '취소',
        'Cancel' : '취소',
        'CANCEL : ' : '취소 : ',
        'SELECT : ' : '선택 : ',
        'UNSELECT : ' : '선택 해제 : ',
        'START' : '시작',
        'Save' : '저장',
        'Tools' : '도구',
        'Settings' : '설정',
        'Packages' : '패키지',
        'Configuration' : '설정',
        'First Settings' : '초기 설정',
        'Custom Songs' : '사용자 정의 곡',
        'Key Press Delay' : '키 입력 딜레이',
        'Sound Delay' : '음원 재생 딜레이',
        'Judge Timing' : '판정 타이밍',
        'Note Location' : '노트 위치',
        'Note Speed Rate' : '노트 속도 배수',
        'Graphic Quality' : '그래픽 품질',
        'Reset All' : '전체 초기화',
        'Reset ALL' : '전체 초기화',
        'Language' : '언어',
        'Quality' : '품질',
        "Line Keys" : '라인 키',
        'Choose your song !' : '곡을 선택하세요 !',
        'Choose your song to listen !' : '감상할 곡을 선택하세요 !',
        'Choose your mission !' : '미션을 선택하세요 !',
        'Choose difficulty !' : '난이도를 선택하세요 !',
        'Choose the level !' : '난이도를 선택하세요 !',
        'No songs available !' : '현재 선택 가능한 곡이 없습니다 !',
        'No records !' : '기록이 없습니다. !',
        'Please select at least one song to listen.' : '감상할 곡을 최소 한 곡 이상 선택하세요.',
        'Composed by %1, Notes written by %2, %3 BPM' : '작곡 : %1, 노트 작성 : %2, %3 BPM',
        'Composed by %1, Notes written by %2' : '작곡 : %1, 노트 작성 : %2',
        'Random song, random notes !' : '랜덤 곡, 랜덤 노트',
        'Survive (EASY)' : '생존 (쉬움)',
        'Survive (NORMAL)' : '생존 (보통)',
        'Survive (HARD)' : '생존 (어려움)',
        'Survive (Very HARD)' : '생존 (매우어려움)',
        'Survive (CRAZY)' : '생존 (CRASY)',
        "PLAY : " : "플레이 : ",
        'BACK : ' : '돌아가기 : ',
        'Go back' : '돌아가기',
        '% key to continue...' : '% 키를 눌러 계속...',
        'PLAYING REPORT' : 'PLAYING REPORT',
        'TOTAL' : 'TOTAL',
        'Visit % for detail...' : '% 에 방문하여 자세한 사항을 확인하세요.',
        'Please wait...' : '잠시 기다려주세요...',
        'PAUSED' : '일시정지',
        'Resume within % !' : '재개 대기 % !',
        '%1 key to resume, %2 key to give up !' : '재개하려면 %1, 포기하려면 %2',
        '%1 key to resume, %2 key to stop !' : '재개하려면 %1, 중지하려면 %2',
        '% key to reset all now !' : '% 키를 다시 누르면 전체 초기화 !',
        '% key to start' : '% 키를 눌러 시작',
        'Touch here to start' : '이 곳을 터치하여 시작',
        'Do you want to reset all?' : '전부 초기화 하시겠습니까?',
        'Modify values, and test it. Press %1 key to save.' : '값을 수정하고 테스트하신 후, %1 키를 눌러 저장하세요 !',
        'You can also test it now !' : '실시간으로 테스트가 가능합니다.',
        'RECORD' : '기록',
        'LOGIN' : '로그인',
        'LOGOUT' : '로그아웃',
        'Do you want to logout now?' : '지금 로그아웃 하시겠습니까?',
        "E-MAIL" : 'E-MAIL',
        "PASSWORD" : '암호',
        "JOIN" : "가입",
        "LOCAL" : "로컬",
        "INTERNET" : "인터넷",
        "GUEST" : "GUEST",
        "LOW" : "낮음",
        "MEDIUM" : "보통",
        "HIGH" : "높음",
        "EXPERIMENTAL" : "실험기능",
        "YES" : "예",
        "NO" : "아니오",
        "Privacy Policy" : "개인정보처리방침",
        "DELETE ACCOUNT" : "탈퇴",
        "Do you want to delete your all informations on this game?" : "이 게임 내에서 당신의 정보를 모두 삭제하시겠습니까?",
        "Logging in means you agree to our Privacy Policy." : "로그인과 동시에 개인정보처리방침에도 동의하시게 됩니다.",
        "COMMUNITY" : "커뮤니티",
        "BOARD" : "게시판",
        "Board" : "게시판",
        "Songs" : "곡 목록",
        "Songs (Open-Source)" : "오픈소스 곡",
        "Play with your own music !" : "보유한 음악으로 즐겨 보세요 !",
        "Scores will not be saved." : "기록이 저장되지 않습니다.",
        "BPM" : "BPM",
        "MUSIC" : "음악",
        "Worker" : "Worker",
        "USE" : "사용",
        "NOT USE" : "사용 안 함",
        "Custom settings here (JSON format)" : '커스텀 설정 (JSON 형식으로 입력)',
        "Open YouTube : " : "유튜브 열기 : ",
        "Content buffer is empty. Please check your network connection." : "콘텐츠 버퍼가 비어있습니다. 네트워크 연결을 확인하세요.",
        "AUTO PLAYING" : "자동 플레이 중",
        "MUSIC SOURCE" : "음원 소스",
        "File" : "파일",
        "URL" : "URL",
        "GitHub : " : "GitHub : ",
        "FIT TIMING" : "타이밍 보정",
        "ADJUST TIMING" : "타이밍 보정",
        "EXIT" : "종료",
        "EXIT : " : "종료 : ",
        "OFFLINE" : "OFFLINE",
        "EMPTY !" : "비어 있음 !",
        "Font" : "글꼴",
        "HOME" : "홈",
        "ETC" : "기타",
        "GitHub" : "GitHub",
        "Launch the game (Popup)" : "게임 실행 (팝업)",
        "Delete your informations on game DB (Popup)" : "게임 DB 내 정보 삭제 (팝업)",
        "Visit the github page (Popup)" : "GitHub 페이지 방문 (팝업)",
        "If you click this, you will see the privacy policy. (Popup)" : "이 버튼을 클릭하면 개인정보처리방침을 확인할 수 있습니다. (팝업)",
        'Please increase the window size.' : '창 크기를 늘려주세요.',
        "Search" : '검색'
    }
};
export { SSStringTable };
export default SSStringTable;