/**
 * Shutting Stars
 * 
 *     기본 탑재 곡들을 구현하는 파일
 */
let song;

song = new ShuttingStarsSong();
song.name = 'Night Ride';
song.composer = 'Joshua Moses';
song.noteWriter = 'HJOW';
song.bgaUrl = '';
song.musicUrl = '/resources/songs/night-ride-by-joshua-moses.mp3';
song.thumbnailUrl = '';
song.description = `
|Music: Night Ride by Joshua Moses
|  https://joshuamosesmusic.bandcamp.com
|License: Creative Commons
|  Attribution 4.0 International — CC BY 4.0
|Free Download
|Stream: https://links.al/NnW
|Music promoted by
|  Audio Library: https://links.al/youtube
`;
song.bpm = 79;
song.endTime = 1838;
song.timeConst = -130;
song.difficulties = {
    'normal;4' : [
        new ShuttingStarsNotePattern(-1, 137  ),
        new ShuttingStarsNotePattern(-1, 145  ),
        new ShuttingStarsNotePattern(-1, 152  ),
        new ShuttingStarsNotePattern(-1, 156  ),
        new ShuttingStarsNotePattern(-1, 158  ),
        new ShuttingStarsNotePattern(-1, 160  ),
        new ShuttingStarsNotePattern(-1, 168  ),
        new ShuttingStarsNotePattern(-1, 176  ),
        new ShuttingStarsNotePattern(-1, 181  ),
        new ShuttingStarsNotePattern(-1, 186  ),
        new ShuttingStarsNotePattern(-1, 188  ),
        new ShuttingStarsNotePattern(-1, 192  ),
        new ShuttingStarsNotePattern(-1, 199  ),
        new ShuttingStarsNotePattern(-1, 207  ),
        new ShuttingStarsNotePattern(-1, 212  ),
        new ShuttingStarsNotePattern(-1, 219  ),
        new ShuttingStarsNotePattern(-1, 220  ),
        new ShuttingStarsNotePattern(-1, 223  ),
        new ShuttingStarsNotePattern(-1, 227  ),
        new ShuttingStarsNotePattern(-1, 231  ),
        new ShuttingStarsNotePattern(-1, 238  ),
        new ShuttingStarsNotePattern(-1, 242  ),
        new ShuttingStarsNotePattern(-1, 249  ),
        new ShuttingStarsNotePattern(-1, 252  ),
        new ShuttingStarsNotePattern(-1, 255  ),
        new ShuttingStarsNotePattern(-1, 259  ),
        new ShuttingStarsNotePattern(-1, 263  ),
        new ShuttingStarsNotePattern(-1, 269  ),
        new ShuttingStarsNotePattern(-1, 275  ),
        new ShuttingStarsNotePattern(-1, 282  ),
        new ShuttingStarsNotePattern(-1, 283  ),
        new ShuttingStarsNotePattern(-1, 287  ),
        new ShuttingStarsNotePattern(-1, 290  ),
        new ShuttingStarsNotePattern(-1, 293  ),
        new ShuttingStarsNotePattern(-1, 300  ),
        new ShuttingStarsNotePattern(-1, 305  ),
        new ShuttingStarsNotePattern(-1, 313  ),
        new ShuttingStarsNotePattern(-1, 314  ),
        new ShuttingStarsNotePattern(-1, 318  ),
        new ShuttingStarsNotePattern(-1, 322  ),
        new ShuttingStarsNotePattern(-1, 326  ),
        new ShuttingStarsNotePattern(-1, 329  ),
        new ShuttingStarsNotePattern(-1, 333  ),
        new ShuttingStarsNotePattern(-1, 337  ),
        new ShuttingStarsNotePattern(-1, 343  ),
        new ShuttingStarsNotePattern(-1, 345  ),
        new ShuttingStarsNotePattern(-1, 349  ),
        new ShuttingStarsNotePattern(-1, 353  ),
        new ShuttingStarsNotePattern(-1, 357  ),
        new ShuttingStarsNotePattern(-1, 361  ),
        new ShuttingStarsNotePattern(-1, 365  ),
        new ShuttingStarsNotePattern(-1, 369  ),
        new ShuttingStarsNotePattern(-1, 375  ),
        new ShuttingStarsNotePattern(-1, 378  ),
        new ShuttingStarsNotePattern(-1, 381  ),
        new ShuttingStarsNotePattern(-1, 385  ),
        new ShuttingStarsNotePattern(-1, 389  ),
        new ShuttingStarsNotePattern(-1, 391  ),
        new ShuttingStarsNotePattern(-1, 393  ),
        new ShuttingStarsNotePattern(-1, 397  ),
        new ShuttingStarsNotePattern(-1, 397  ),
        new ShuttingStarsNotePattern(-1, 401  ),
        new ShuttingStarsNotePattern(-1, 408  ),
        new ShuttingStarsNotePattern(-1, 410  ),
        new ShuttingStarsNotePattern(-1, 413  ),
        new ShuttingStarsNotePattern(-1, 417  ),
        new ShuttingStarsNotePattern(-1, 421  ),
        new ShuttingStarsNotePattern(-1, 425  ),
        new ShuttingStarsNotePattern(-1, 428  ),
        new ShuttingStarsNotePattern(-1, 432  ),
        new ShuttingStarsNotePattern(-1, 438  ),
        new ShuttingStarsNotePattern(-1, 440  ),
        new ShuttingStarsNotePattern(-1, 444  ),
        new ShuttingStarsNotePattern(-1, 453  ),
        new ShuttingStarsNotePattern(-1, 457  ),
        new ShuttingStarsNotePattern(-1, 460  ),
        new ShuttingStarsNotePattern(-1, 464  ),
        new ShuttingStarsNotePattern(-1, 471  ),
        new ShuttingStarsNotePattern(-1, 472  ),
        new ShuttingStarsNotePattern(-1, 476  ),
        new ShuttingStarsNotePattern(-1, 480  ),
        new ShuttingStarsNotePattern(-1, 483  ),
        new ShuttingStarsNotePattern(-1, 487  ),
        new ShuttingStarsNotePattern(-1, 491  ),
        new ShuttingStarsNotePattern(-1, 495  ),
        new ShuttingStarsNotePattern(-1, 502  ),
        new ShuttingStarsNotePattern(-1, 504  ),
        new ShuttingStarsNotePattern(-1, 507  ),
        new ShuttingStarsNotePattern(-1, 515  ),
        new ShuttingStarsNotePattern(-1, 524  ),
        new ShuttingStarsNotePattern(-1, 527  ),
        new ShuttingStarsNotePattern(-1, 534  ),
        new ShuttingStarsNotePattern(-1, 536  ),
        new ShuttingStarsNotePattern(-1, 540  ),
        new ShuttingStarsNotePattern(-1, 543  ),
        new ShuttingStarsNotePattern(-1, 547  ),
        new ShuttingStarsNotePattern(-1, 554  ),
        new ShuttingStarsNotePattern(-1, 561  ),
        new ShuttingStarsNotePattern(-1, 566  ),
        new ShuttingStarsNotePattern(-1, 568  ),
        new ShuttingStarsNotePattern(-1, 571  ),
        new ShuttingStarsNotePattern(-1, 574  ),
        new ShuttingStarsNotePattern(-1, 578  ),
        new ShuttingStarsNotePattern(-1, 586  ),
        new ShuttingStarsNotePattern(-1, 590  ),
        new ShuttingStarsNotePattern(-1, 597  ),
        new ShuttingStarsNotePattern(-1, 599  ),
        new ShuttingStarsNotePattern(-1, 602  ),
        new ShuttingStarsNotePattern(-1, 606  ),
        new ShuttingStarsNotePattern(-1, 609  ),
        new ShuttingStarsNotePattern(-1, 613  ),
        new ShuttingStarsNotePattern(-1, 618  ),
        new ShuttingStarsNotePattern(-1, 621  ),
        new ShuttingStarsNotePattern(-1, 628  ),
        new ShuttingStarsNotePattern(-1, 630  ),
        new ShuttingStarsNotePattern(-1, 633  ),
        new ShuttingStarsNotePattern(-1, 638  ),
        new ShuttingStarsNotePattern(-1, 641  ),
        new ShuttingStarsNotePattern(-1, 649  ),
        new ShuttingStarsNotePattern(-1, 654  ),
        new ShuttingStarsNotePattern(-1, 661  ),
        new ShuttingStarsNotePattern(-1, 662  ),
        new ShuttingStarsNotePattern(-1, 666  ),
        new ShuttingStarsNotePattern(-1, 669  ),
        new ShuttingStarsNotePattern(-1, 673  ),
        new ShuttingStarsNotePattern(-1, 680  ),
        new ShuttingStarsNotePattern(-1, 685  ),
        new ShuttingStarsNotePattern(-1, 693  ),
        new ShuttingStarsNotePattern(-1, 697  ),
        new ShuttingStarsNotePattern(-1, 705  ),
        new ShuttingStarsNotePattern(-1, 705  ),
        new ShuttingStarsNotePattern(-1, 713  ),
        new ShuttingStarsNotePattern(-1, 721  ),
        new ShuttingStarsNotePattern(-1, 729  ),
        new ShuttingStarsNotePattern(-1, 737  ),
        new ShuttingStarsNotePattern(-1, 737  ),
        new ShuttingStarsNotePattern(-1, 744  ),
        new ShuttingStarsNotePattern(-1, 748  ),
        new ShuttingStarsNotePattern(-1, 760  ),
        new ShuttingStarsNotePattern(-1, 768  ),
        new ShuttingStarsNotePattern(-1, 776  ),
        new ShuttingStarsNotePattern(-1, 780  ),
        new ShuttingStarsNotePattern(-1, 791  ),
        new ShuttingStarsNotePattern(-1, 800  ),
        new ShuttingStarsNotePattern(-1, 807  ),
        new ShuttingStarsNotePattern(-1, 811  ),
        new ShuttingStarsNotePattern(-1, 824  ),
        new ShuttingStarsNotePattern(-1, 832  ),
        new ShuttingStarsNotePattern(-1, 840  ),
        new ShuttingStarsNotePattern(-1, 843  ),
        new ShuttingStarsNotePattern(-1, 855  ),
        new ShuttingStarsNotePattern(-1, 859  ),
        new ShuttingStarsNotePattern(-1, 863  ),
        new ShuttingStarsNotePattern(-1, 870  ),
        new ShuttingStarsNotePattern(-1, 874  ),
        new ShuttingStarsNotePattern(-1, 883  ),
        new ShuttingStarsNotePattern(-1, 886  ),
        new ShuttingStarsNotePattern(-1, 890  ),
        new ShuttingStarsNotePattern(-1, 894  ),
        new ShuttingStarsNotePattern(-1, 902  ),
        new ShuttingStarsNotePattern(-1, 906  ),
        new ShuttingStarsNotePattern(-1, 915  ),
        new ShuttingStarsNotePattern(-1, 918  ),
        new ShuttingStarsNotePattern(-1, 922  ),
        new ShuttingStarsNotePattern(-1, 926  ),
        new ShuttingStarsNotePattern(-1, 933  ),
        new ShuttingStarsNotePattern(-1, 937  ),
        new ShuttingStarsNotePattern(-1, 941  ),
        new ShuttingStarsNotePattern(-1, 946  ),
        new ShuttingStarsNotePattern(-1, 948  ),
        new ShuttingStarsNotePattern(-1, 950  ),
        new ShuttingStarsNotePattern(-1, 953  ),
        new ShuttingStarsNotePattern(-1, 958  ),
        new ShuttingStarsNotePattern(-1, 966  ),
        new ShuttingStarsNotePattern(-1, 970  ),
        new ShuttingStarsNotePattern(-1, 976  ),
        new ShuttingStarsNotePattern(-1, 978  ),
        new ShuttingStarsNotePattern(-1, 981  ),
        new ShuttingStarsNotePattern(-1, 985  ),
        new ShuttingStarsNotePattern(-1, 989  ),
        new ShuttingStarsNotePattern(-1, 996  ),
        new ShuttingStarsNotePattern(-1, 1001 ),
        new ShuttingStarsNotePattern(-1, 1007 ),
        new ShuttingStarsNotePattern(-1, 1009 ),
        new ShuttingStarsNotePattern(-1, 1012 ),
        new ShuttingStarsNotePattern(-1, 1017 ),
        new ShuttingStarsNotePattern(-1, 1021 ),
        new ShuttingStarsNotePattern(-1, 1028 ),
        new ShuttingStarsNotePattern(-1, 1033 ),
        new ShuttingStarsNotePattern(-1, 1039 ),
        new ShuttingStarsNotePattern(-1, 1041 ),
        new ShuttingStarsNotePattern(-1, 1044 ),
        new ShuttingStarsNotePattern(-1, 1048 ),
        new ShuttingStarsNotePattern(-1, 1052 ),
        new ShuttingStarsNotePattern(-1, 1059 ),
        new ShuttingStarsNotePattern(-1, 1065 ),
        new ShuttingStarsNotePattern(-1, 1071 ),
        new ShuttingStarsNotePattern(-1, 1073 ),
        new ShuttingStarsNotePattern(-1, 1076 ),
        new ShuttingStarsNotePattern(-1, 1080 ),
        new ShuttingStarsNotePattern(-1, 1084 ),
        new ShuttingStarsNotePattern(-1, 1091 ),
        new ShuttingStarsNotePattern(-1, 1096 ),
        new ShuttingStarsNotePattern(-1, 1103 ),
        new ShuttingStarsNotePattern(-1, 1105 ),
        new ShuttingStarsNotePattern(-1, 1108 ),
        new ShuttingStarsNotePattern(-1, 1112 ),
        new ShuttingStarsNotePattern(-1, 1116 ),
        new ShuttingStarsNotePattern(-1, 1123 ),
        new ShuttingStarsNotePattern(-1, 1128 ),
        new ShuttingStarsNotePattern(-1, 1134 ),
        new ShuttingStarsNotePattern(-1, 1136 ),
        new ShuttingStarsNotePattern(-1, 1139 ),
        new ShuttingStarsNotePattern(-1, 1143 ),
        new ShuttingStarsNotePattern(-1, 1147 ),
        new ShuttingStarsNotePattern(-1, 1153 ),
        new ShuttingStarsNotePattern(-1, 1159 ),
        new ShuttingStarsNotePattern(-1, 1166 ),
        new ShuttingStarsNotePattern(-1, 1168 ),
        new ShuttingStarsNotePattern(-1, 1171 ),
        new ShuttingStarsNotePattern(-1, 1175 ),
        new ShuttingStarsNotePattern(-1, 1179 ),
        new ShuttingStarsNotePattern(-1, 1186 ),
        new ShuttingStarsNotePattern(-1, 1187 ),
        new ShuttingStarsNotePattern(-1, 1191 ),
        new ShuttingStarsNotePattern(-1, 1197 ),
        new ShuttingStarsNotePattern(-1, 1198 ),
        new ShuttingStarsNotePattern(-1, 1202 ),
        new ShuttingStarsNotePattern(-1, 1203 ),
        new ShuttingStarsNotePattern(-1, 1210 ),
        new ShuttingStarsNotePattern(-1, 1218 ),
        new ShuttingStarsNotePattern(-1, 1222 ),
        new ShuttingStarsNotePattern(-1, 1229 ),
        new ShuttingStarsNotePattern(-1, 1231 ),
        new ShuttingStarsNotePattern(-1, 1234 ),
        new ShuttingStarsNotePattern(-1, 1238 ),
        new ShuttingStarsNotePattern(-1, 1242 ),
        new ShuttingStarsNotePattern(-1, 1249 ),
        new ShuttingStarsNotePattern(-1, 1254 ),
        new ShuttingStarsNotePattern(-1, 1260 ),
        new ShuttingStarsNotePattern(-1, 1262 ),
        new ShuttingStarsNotePattern(-1, 1266 ),
        new ShuttingStarsNotePattern(-1, 1269 ),
        new ShuttingStarsNotePattern(-1, 1273 ),
        new ShuttingStarsNotePattern(-1, 1281 ),
        new ShuttingStarsNotePattern(-1, 1285 ),
        new ShuttingStarsNotePattern(-1, 1292 ),
        new ShuttingStarsNotePattern(-1, 1294 ),
        new ShuttingStarsNotePattern(-1, 1297 ),
        new ShuttingStarsNotePattern(-1, 1301 ),
        new ShuttingStarsNotePattern(-1, 1305 ),
        new ShuttingStarsNotePattern(-1, 1312 ),
        new ShuttingStarsNotePattern(-1, 1316 ),
        new ShuttingStarsNotePattern(-1, 1323 ),
        new ShuttingStarsNotePattern(-1, 1325 ),
        new ShuttingStarsNotePattern(-1, 1328 ),
        new ShuttingStarsNotePattern(-1, 1332 ),
        new ShuttingStarsNotePattern(-1, 1336 ),
        new ShuttingStarsNotePattern(-1, 1344 ),
        new ShuttingStarsNotePattern(-1, 1349 ),
        new ShuttingStarsNotePattern(-1, 1356 ),
        new ShuttingStarsNotePattern(-1, 1357 ),
        new ShuttingStarsNotePattern(-1, 1361 ),
        new ShuttingStarsNotePattern(-1, 1364 ),
        new ShuttingStarsNotePattern(-1, 1368 ),
        new ShuttingStarsNotePattern(-1, 1372 ),
        new ShuttingStarsNotePattern(-1, 1376 ),
        new ShuttingStarsNotePattern(-1, 1379 ),
        new ShuttingStarsNotePattern(-1, 1386 ),
        new ShuttingStarsNotePattern(-1, 1387 ),
        new ShuttingStarsNotePattern(-1, 1391 ),
        new ShuttingStarsNotePattern(-1, 1395 ),
        new ShuttingStarsNotePattern(-1, 1399 ),
        new ShuttingStarsNotePattern(-1, 1403 ),
        new ShuttingStarsNotePattern(-1, 1407 ),
        new ShuttingStarsNotePattern(-1, 1412 ),
        new ShuttingStarsNotePattern(-1, 1418 ),
        new ShuttingStarsNotePattern(-1, 1420 ),
        new ShuttingStarsNotePattern(-1, 1423 ),
        new ShuttingStarsNotePattern(-1, 1427 ),
        new ShuttingStarsNotePattern(-1, 1431 ),
        new ShuttingStarsNotePattern(-1, 1435 ),
        new ShuttingStarsNotePattern(-1, 1439 ),
        new ShuttingStarsNotePattern(-1, 1443 ),
        new ShuttingStarsNotePattern(-1, 1447 ),
        new ShuttingStarsNotePattern(-1, 1452 ),
        new ShuttingStarsNotePattern(-1, 1456 ),
        new ShuttingStarsNotePattern(-1, 1527 ),
        new ShuttingStarsNotePattern(-1, 1535 ),
        new ShuttingStarsNotePattern(-1, 1538 ),
        new ShuttingStarsNotePattern(-1, 1553 ),
        new ShuttingStarsNotePattern(-1, 1559 ),
        new ShuttingStarsNotePattern(-1, 1567 ),
        new ShuttingStarsNotePattern(-1, 1570 ),
        new ShuttingStarsNotePattern(-1, 1582 ),
        new ShuttingStarsNotePattern(-1, 1652 ),
        new ShuttingStarsNotePattern(-1, 1660 ),
        new ShuttingStarsNotePattern(-1, 1664 ),
        new ShuttingStarsNotePattern(-1, 1672 ),
        new ShuttingStarsNotePattern(-1, 1675 ),
        new ShuttingStarsNotePattern(-1, 1680 ),
        new ShuttingStarsNotePattern(-1, 1683 ),
        new ShuttingStarsNotePattern(-1, 1691 ),
        new ShuttingStarsNotePattern(-1, 1695 ),
        new ShuttingStarsNotePattern(-1, 1707 )
    ]
};
_shuttingstarcore.songs.push(song);

song = new ShuttingStarsSong();
song.name = 'TEST SONG';
song.composer = 'HJOW';
song.noteWriter = 'HJOW';
song.bgaUrl = '';
song.musicUrl = '';
song.thumbnailUrl = '';
song.description = 'Just for test this game';
song.bpm = 120;
song.endTime = 540;
song.timeConst = 0;
song.difficulties = {
    'hard;9' : []
};

// 임시 테스트 곡으로, 노트는 랜덤하게 생성
for(let idx=0; idx<song.endTime; idx++) {
    const pattern = new ShuttingStarsNotePattern(-1, idx);
    
    if(Math.random() > 0.2) song.difficulties['hard;9'].push(pattern);
}

_shuttingstarcore.songs.push(song);