/**
 * Shutting Stars
 * 
 *     기본 탑재 곡들을 구현하는 파일
 */
let song;

song = {};
song.name = 'Night Ride';
song.composer = 'Joshua Moses';
song.noteWriter = 'HJOW';
song.bgaUrl = '';
song.musicUrl = './resources/songs/night-ride-by-joshua-moses.mp3';
song.thumbnailUrl = '';
song.description = `
|Music: Night Ride by Joshua Moses
|  https://joshuamosesmusic.bandcamp.com
|License: Creative Commons
|  Attribution 4.0 International — CC BY 4.0
|Free Download
|Stream: https://links.al/NnW
|Music promoted by
|  Audio Library: https://links.al/youtube
`;
song.bpm = 79;
song.endTime = 1838;
song.timeConstant = -135;
song.timeMultiplier = 2;
song.difficulties = {
    'normal;4' : [
        { locationIndex : -1, time : 137  },
        { locationIndex : -1, time : 145  },
        { locationIndex : -1, time : 152  },
        { locationIndex : -1, time : 156  },
        { locationIndex : -1, time : 158  },
        { locationIndex : -1, time : 160  },
        { locationIndex : -1, time : 168  },
        { locationIndex : -1, time : 176  },
        { locationIndex : -1, time : 181  },
        { locationIndex : -1, time : 186  },
        { locationIndex : -1, time : 188  },
        { locationIndex : -1, time : 192  },
        { locationIndex : -1, time : 199  },
        { locationIndex : -1, time : 207  },
        { locationIndex : -1, time : 212  },
        { locationIndex : -1, time : 219  },
        { locationIndex : -1, time : 220  },
        { locationIndex : -1, time : 223  },
        { locationIndex : -1, time : 227  },
        { locationIndex : -1, time : 231  },
        { locationIndex : -1, time : 238  },
        { locationIndex : -1, time : 242  },
        { locationIndex : -1, time : 249  },
        { locationIndex : -1, time : 252  },
        { locationIndex : -1, time : 255  },
        { locationIndex : -1, time : 259  },
        { locationIndex : -1, time : 263  },
        { locationIndex : -1, time : 269  },
        { locationIndex : -1, time : 275  },
        { locationIndex : -1, time : 282  },
        { locationIndex : -1, time : 283  },
        { locationIndex : -1, time : 287  },
        { locationIndex : -1, time : 290  },
        { locationIndex : -1, time : 293  },
        { locationIndex : -1, time : 300  },
        { locationIndex : -1, time : 305  },
        { locationIndex : -1, time : 313  },
        { locationIndex : -1, time : 314  },
        { locationIndex : -1, time : 318  },
        { locationIndex : -1, time : 322  },
        { locationIndex : -1, time : 326  },
        { locationIndex : -1, time : 329  },
        { locationIndex : -1, time : 333  },
        { locationIndex : -1, time : 337  },
        { locationIndex : -1, time : 343  },
        { locationIndex : -1, time : 345  },
        { locationIndex : -1, time : 349  },
        { locationIndex : -1, time : 353  },
        { locationIndex : -1, time : 357  },
        { locationIndex : -1, time : 361  },
        { locationIndex : -1, time : 365  },
        { locationIndex : -1, time : 369  },
        { locationIndex : -1, time : 375  },
        { locationIndex : -1, time : 378  },
        { locationIndex : -1, time : 381  },
        { locationIndex : -1, time : 385  },
        { locationIndex : -1, time : 389  },
        { locationIndex : -1, time : 391  },
        { locationIndex : -1, time : 393  },
        { locationIndex : -1, time : 397  },
        { locationIndex : -1, time : 397  },
        { locationIndex : -1, time : 401  },
        { locationIndex : -1, time : 408  },
        { locationIndex : -1, time : 410  },
        { locationIndex : -1, time : 413  },
        { locationIndex : -1, time : 417  },
        { locationIndex : -1, time : 421  },
        { locationIndex : -1, time : 425  },
        { locationIndex : -1, time : 428  },
        { locationIndex : -1, time : 432  },
        { locationIndex : -1, time : 438  },
        { locationIndex : -1, time : 440  },
        { locationIndex : -1, time : 444  },
        { locationIndex : -1, time : 453  },
        { locationIndex : -1, time : 457  },
        { locationIndex : -1, time : 460  },
        { locationIndex : -1, time : 464  },
        { locationIndex : -1, time : 471  },
        { locationIndex : -1, time : 472  },
        { locationIndex : -1, time : 476  },
        { locationIndex : -1, time : 480  },
        { locationIndex : -1, time : 483  },
        { locationIndex : -1, time : 487  },
        { locationIndex : -1, time : 491  },
        { locationIndex : -1, time : 495  },
        { locationIndex : -1, time : 502  },
        { locationIndex : -1, time : 504  },
        { locationIndex : -1, time : 507  },
        { locationIndex : -1, time : 515  },
        { locationIndex : -1, time : 524  },
        { locationIndex : -1, time : 527  },
        { locationIndex : -1, time : 534  },
        { locationIndex : -1, time : 536  },
        { locationIndex : -1, time : 540  },
        { locationIndex : -1, time : 543  },
        { locationIndex : -1, time : 547  },
        { locationIndex : -1, time : 554  },
        { locationIndex : -1, time : 561  },
        { locationIndex : -1, time : 566  },
        { locationIndex : -1, time : 568  },
        { locationIndex : -1, time : 571  },
        { locationIndex : -1, time : 574  },
        { locationIndex : -1, time : 578  },
        { locationIndex : -1, time : 586  },
        { locationIndex : -1, time : 590  },
        { locationIndex : -1, time : 597  },
        { locationIndex : -1, time : 599  },
        { locationIndex : -1, time : 602  },
        { locationIndex : -1, time : 606  },
        { locationIndex : -1, time : 609  },
        { locationIndex : -1, time : 613  },
        { locationIndex : -1, time : 618  },
        { locationIndex : -1, time : 621  },
        { locationIndex : -1, time : 628  },
        { locationIndex : -1, time : 630  },
        { locationIndex : -1, time : 633  },
        { locationIndex : -1, time : 638  },
        { locationIndex : -1, time : 641  },
        { locationIndex : -1, time : 649  },
        { locationIndex : -1, time : 654  },
        { locationIndex : -1, time : 661  },
        { locationIndex : -1, time : 662  },
        { locationIndex : -1, time : 666  },
        { locationIndex : -1, time : 669  },
        { locationIndex : -1, time : 673  },
        { locationIndex : -1, time : 680  },
        { locationIndex : -1, time : 685  },
        { locationIndex : -1, time : 693  },
        { locationIndex : -1, time : 697  },
        { locationIndex : -1, time : 705  },
        { locationIndex : -1, time : 705  },
        { locationIndex : -1, time : 713  },
        { locationIndex : -1, time : 721  },
        { locationIndex : -1, time : 729  },
        { locationIndex : -1, time : 737  },
        { locationIndex : -1, time : 737  },
        { locationIndex : -1, time : 744  },
        { locationIndex : -1, time : 748  },
        { locationIndex : -1, time : 760  },
        { locationIndex : -1, time : 768  },
        { locationIndex : -1, time : 776  },
        { locationIndex : -1, time : 780  },
        { locationIndex : -1, time : 791  },
        { locationIndex : -1, time : 800  },
        { locationIndex : -1, time : 807  },
        { locationIndex : -1, time : 811  },
        { locationIndex : -1, time : 824  },
        { locationIndex : -1, time : 832  },
        { locationIndex : -1, time : 840  },
        { locationIndex : -1, time : 843  },
        { locationIndex : -1, time : 855  },
        { locationIndex : -1, time : 859  },
        { locationIndex : -1, time : 863  },
        { locationIndex : -1, time : 870  },
        { locationIndex : -1, time : 874  },
        { locationIndex : -1, time : 883  },
        { locationIndex : -1, time : 886  },
        { locationIndex : -1, time : 890  },
        { locationIndex : -1, time : 894  },
        { locationIndex : -1, time : 902  },
        { locationIndex : -1, time : 906  },
        { locationIndex : -1, time : 915  },
        { locationIndex : -1, time : 918  },
        { locationIndex : -1, time : 922  },
        { locationIndex : -1, time : 926  },
        { locationIndex : -1, time : 933  },
        { locationIndex : -1, time : 937  },
        { locationIndex : -1, time : 941  },
        { locationIndex : -1, time : 946  },
        { locationIndex : -1, time : 948  },
        { locationIndex : -1, time : 950  },
        { locationIndex : -1, time : 953  },
        { locationIndex : -1, time : 958  },
        { locationIndex : -1, time : 966  },
        { locationIndex : -1, time : 970  },
        { locationIndex : -1, time : 976  },
        { locationIndex : -1, time : 978  },
        { locationIndex : -1, time : 981  },
        { locationIndex : -1, time : 985  },
        { locationIndex : -1, time : 989  },
        { locationIndex : -1, time : 996  },
        { locationIndex : -1, time : 1001 },
        { locationIndex : -1, time : 1007 },
        { locationIndex : -1, time : 1009 },
        { locationIndex : -1, time : 1012 },
        { locationIndex : -1, time : 1017 },
        { locationIndex : -1, time : 1021 },
        { locationIndex : -1, time : 1028 },
        { locationIndex : -1, time : 1033 },
        { locationIndex : -1, time : 1039 },
        { locationIndex : -1, time : 1041 },
        { locationIndex : -1, time : 1044 },
        { locationIndex : -1, time : 1048 },
        { locationIndex : -1, time : 1052 },
        { locationIndex : -1, time : 1059 },
        { locationIndex : -1, time : 1065 },
        { locationIndex : -1, time : 1071 },
        { locationIndex : -1, time : 1073 },
        { locationIndex : -1, time : 1076 },
        { locationIndex : -1, time : 1080 },
        { locationIndex : -1, time : 1084 },
        { locationIndex : -1, time : 1091 },
        { locationIndex : -1, time : 1096 },
        { locationIndex : -1, time : 1103 },
        { locationIndex : -1, time : 1105 },
        { locationIndex : -1, time : 1108 },
        { locationIndex : -1, time : 1112 },
        { locationIndex : -1, time : 1116 },
        { locationIndex : -1, time : 1123 },
        { locationIndex : -1, time : 1128 },
        { locationIndex : -1, time : 1134 },
        { locationIndex : -1, time : 1136 },
        { locationIndex : -1, time : 1139 },
        { locationIndex : -1, time : 1143 },
        { locationIndex : -1, time : 1147 },
        { locationIndex : -1, time : 1153 },
        { locationIndex : -1, time : 1159 },
        { locationIndex : -1, time : 1166 },
        { locationIndex : -1, time : 1168 },
        { locationIndex : -1, time : 1171 },
        { locationIndex : -1, time : 1175 },
        { locationIndex : -1, time : 1179 },
        { locationIndex : -1, time : 1186 },
        { locationIndex : -1, time : 1187 },
        { locationIndex : -1, time : 1191 },
        { locationIndex : -1, time : 1197 },
        { locationIndex : -1, time : 1198 },
        { locationIndex : -1, time : 1202 },
        { locationIndex : -1, time : 1203 },
        { locationIndex : -1, time : 1210 },
        { locationIndex : -1, time : 1218 },
        { locationIndex : -1, time : 1222 },
        { locationIndex : -1, time : 1229 },
        { locationIndex : -1, time : 1231 },
        { locationIndex : -1, time : 1234 },
        { locationIndex : -1, time : 1238 },
        { locationIndex : -1, time : 1242 },
        { locationIndex : -1, time : 1249 },
        { locationIndex : -1, time : 1254 },
        { locationIndex : -1, time : 1260 },
        { locationIndex : -1, time : 1262 },
        { locationIndex : -1, time : 1266 },
        { locationIndex : -1, time : 1269 },
        { locationIndex : -1, time : 1273 },
        { locationIndex : -1, time : 1281 },
        { locationIndex : -1, time : 1285 },
        { locationIndex : -1, time : 1292 },
        { locationIndex : -1, time : 1294 },
        { locationIndex : -1, time : 1297 },
        { locationIndex : -1, time : 1301 },
        { locationIndex : -1, time : 1305 },
        { locationIndex : -1, time : 1312 },
        { locationIndex : -1, time : 1316 },
        { locationIndex : -1, time : 1323 },
        { locationIndex : -1, time : 1325 },
        { locationIndex : -1, time : 1328 },
        { locationIndex : -1, time : 1332 },
        { locationIndex : -1, time : 1336 },
        { locationIndex : -1, time : 1344 },
        { locationIndex : -1, time : 1349 },
        { locationIndex : -1, time : 1356 },
        { locationIndex : -1, time : 1357 },
        { locationIndex : -1, time : 1361 },
        { locationIndex : -1, time : 1364 },
        { locationIndex : -1, time : 1368 },
        { locationIndex : -1, time : 1372 },
        { locationIndex : -1, time : 1376 },
        { locationIndex : -1, time : 1379 },
        { locationIndex : -1, time : 1386 },
        { locationIndex : -1, time : 1387 },
        { locationIndex : -1, time : 1391 },
        { locationIndex : -1, time : 1395 },
        { locationIndex : -1, time : 1399 },
        { locationIndex : -1, time : 1403 },
        { locationIndex : -1, time : 1407 },
        { locationIndex : -1, time : 1412 },
        { locationIndex : -1, time : 1418 },
        { locationIndex : -1, time : 1420 },
        { locationIndex : -1, time : 1423 },
        { locationIndex : -1, time : 1427 },
        { locationIndex : -1, time : 1431 },
        { locationIndex : -1, time : 1435 },
        { locationIndex : -1, time : 1439 },
        { locationIndex : -1, time : 1443 },
        { locationIndex : -1, time : 1447 },
        { locationIndex : -1, time : 1452 },
        { locationIndex : -1, time : 1456 },
        { locationIndex : -1, time : 1527 },
        { locationIndex : -1, time : 1535 },
        { locationIndex : -1, time : 1538 },
        { locationIndex : -1, time : 1553 },
        { locationIndex : -1, time : 1559 },
        { locationIndex : -1, time : 1567 },
        { locationIndex : -1, time : 1570 },
        { locationIndex : -1, time : 1582 },
        { locationIndex : -1, time : 1652 },
        { locationIndex : -1, time : 1660 },
        { locationIndex : -1, time : 1664 },
        { locationIndex : -1, time : 1672 },
        { locationIndex : -1, time : 1675 },
        { locationIndex : -1, time : 1680 },
        { locationIndex : -1, time : 1683 },
        { locationIndex : -1, time : 1691 },
        { locationIndex : -1, time : 1695 },
        { locationIndex : -1, time : 1707 }
    ]
}

addShuttingStarSong(song);

/*
song = new ShuttingStarsSong();
song.name = 'TEST SONG';
song.composer = 'HJOW';
song.noteWriter = 'HJOW';
song.bgaUrl = '';
song.musicUrl = '';
song.thumbnailUrl = '';
song.description = 'Just for test this game';
song.bpm = 120;
song.endTime = 540;
song.timeConstant = 0;
song.timeMultiplier = 2;
song.difficulties = {
    'hard;9' : []
};

// 임시 테스트 곡으로, 노트는 랜덤하게 생성
for(let idx=0; idx<song.endTime; idx++) {
    const pattern = new ShuttingStarsNotePattern(-1, idx);
    
    if(Math.random() > 0.2) song.difficulties['hard;9'].push(pattern);
}

_shuttingstarcore.songs.push(song);
*/