/**
 * Shutting Stars
 * 
 *     기본 탑재 곡들을 구현하는 파일
 */
let song;

song = {};
song.name = 'Night Ride';
song.composer = 'Joshua Moses';
song.noteWriter = 'HJOW';
song.bgaUrl = '';
song.musicUrl = './resources/songs/night-ride-by-joshua-moses.mp3';
song.thumbnailUrl = '';
song.description = `
|Music: Night Ride by Joshua Moses
|  https://joshuamosesmusic.bandcamp.com
|License: Creative Commons
|  Attribution 4.0 International — CC BY 4.0
|Free Download
|Stream: https://links.al/NnW
|Music promoted by
|  Audio Library: https://links.al/youtube
`;
song.loadingTime = 10;
song.bpm = 79;
song.endTime = 3700;
song.timeConstant = -337;
song.timeMultiplier = 1;
song.serial = 'nai4ilaHbn7g93gn34nf9afn438zJ93f8gp34qgD39p4g';
song.difficulties = [
    {
        difficultyLabel : 'easy',
        difficultyLevel : 4,
        patterns : [
            { locationIndex : -1, time : 404},
            { locationIndex : -1, time : 419},
            { locationIndex : -1, time : 449},
            { locationIndex : -1, time : 466},
            { locationIndex : -1, time : 482},
            { locationIndex : -1, time : 513},
            { locationIndex : -1, time : 531},
            { locationIndex : -1, time : 547},
            { locationIndex : -1, time : 577},
            { locationIndex : -1, time : 594},
            { locationIndex : -1, time : 609},
            { locationIndex : -1, time : 641},
            { locationIndex : -1, time : 658},
            { locationIndex : -1, time : 674},
            { locationIndex : -1, time : 705},
            { locationIndex : -1, time : 721},
            { locationIndex : -1, time : 737},
            { locationIndex : -1, time : 768},
            { locationIndex : -1, time : 786},
            { locationIndex : -1, time : 802},
            { locationIndex : -1, time : 833},
            { locationIndex : -1, time : 849},
            { locationIndex : -1, time : 864},
            { locationIndex : -1, time : 897},
            { locationIndex : -1, time : 914},
            { locationIndex : -1, time : 930},
            { locationIndex : -1, time : 960},
            { locationIndex : -1, time : 976},
            { locationIndex : -1, time : 991},
            { locationIndex : -1, time : 1025},
            { locationIndex : -1, time : 1041},
            { locationIndex : -1, time : 1057},
            { locationIndex : -1, time : 1088},
            { locationIndex : -1, time : 1105},
            { locationIndex : -1, time : 1119},
            { locationIndex : -1, time : 1152},
            { locationIndex : -1, time : 1168},
            { locationIndex : -1, time : 1184},
            { locationIndex : -1, time : 1216},
            { locationIndex : -1, time : 1231},
            { locationIndex : -1, time : 1247},
            { locationIndex : -1, time : 1280},
            { locationIndex : -1, time : 1296},
            { locationIndex : -1, time : 1312},
            { locationIndex : -1, time : 1343},
            { locationIndex : -1, time : 1359},
            { locationIndex : -1, time : 1374},
            { locationIndex : -1, time : 1408},
            { locationIndex : -1, time : 1440},
            { locationIndex : -1, time : 1471},
            { locationIndex : -1, time : 1503},
            { locationIndex : -1, time : 1536},
            { locationIndex : -1, time : 1567},
            { locationIndex : -1, time : 1599},
            { locationIndex : -1, time : 1630},
            { locationIndex : -1, time : 1663},
            { locationIndex : -1, time : 1694},
            { locationIndex : -1, time : 1726},
            { locationIndex : -1, time : 1758},
            { locationIndex : -1, time : 1791},
            { locationIndex : -1, time : 1822},
            { locationIndex : -1, time : 1854},
            { locationIndex : -1, time : 1871},
            { locationIndex : -1, time : 1888},
            { locationIndex : -1, time : 1918},
            { locationIndex : -1, time : 1936},
            { locationIndex : -1, time : 1951},
            { locationIndex : -1, time : 1981},
            { locationIndex : -1, time : 1997},
            { locationIndex : -1, time : 2013},
            { locationIndex : -1, time : 2045},
            { locationIndex : -1, time : 2062},
            { locationIndex : -1, time : 2078},
            { locationIndex : -1, time : 2110},
            { locationIndex : -1, time : 2126},
            { locationIndex : -1, time : 2141},
            { locationIndex : -1, time : 2151},
            { locationIndex : -1, time : 2173},
            { locationIndex : -1, time : 2190},
            { locationIndex : -1, time : 2206},
            { locationIndex : -1, time : 2237},
            { locationIndex : -1, time : 2253},
            { locationIndex : -1, time : 2268},
            { locationIndex : -1, time : 2301},
            { locationIndex : -1, time : 2317},
            { locationIndex : -1, time : 2333},
            { locationIndex : -1, time : 2365},
            { locationIndex : -1, time : 2381},
            { locationIndex : -1, time : 2396},
            { locationIndex : -1, time : 2429},
            { locationIndex : -1, time : 2445},
            { locationIndex : -1, time : 2462},
            { locationIndex : -1, time : 2492},
            { locationIndex : -1, time : 2508},
            { locationIndex : -1, time : 2523},
            { locationIndex : -1, time : 2556},
            { locationIndex : -1, time : 2572},
            { locationIndex : -1, time : 2589},
            { locationIndex : -1, time : 2621},
            { locationIndex : -1, time : 2637},
            { locationIndex : -1, time : 2651},
            { locationIndex : -1, time : 2660},
            { locationIndex : -1, time : 2674},
            { locationIndex : -1, time : 2677},
            { locationIndex : -1, time : 2685},
            { locationIndex : -1, time : 2700},
            { locationIndex : -1, time : 2716},
            { locationIndex : -1, time : 2748},
            { locationIndex : -1, time : 2763},
            { locationIndex : -1, time : 2811},
            { locationIndex : -1, time : 2827},
            { locationIndex : -1, time : 2843},
            { locationIndex : -1, time : 2853},
            { locationIndex : -1, time : 2875},
            { locationIndex : -1, time : 2891},
            { locationIndex : -1, time : 2906},
            { locationIndex : -1, time : 2914},
            { locationIndex : -1, time : 2939},
            { locationIndex : -1, time : 2956},
            { locationIndex : -1, time : 2979},
            { locationIndex : -1, time : 3004},
            { locationIndex : -1, time : 3011},
            { locationIndex : -1, time : 3019},
            { locationIndex : -1, time : 3035},
            { locationIndex : -1, time : 3067},
            { locationIndex : -1, time : 3074},
            { locationIndex : -1, time : 3084},
            { locationIndex : -1, time : 3099},
            { locationIndex : -1, time : 3107},
            { locationIndex : -1, time : 3132},
            { locationIndex : -1, time : 3147},
            { locationIndex : -1, time : 3162},
            { locationIndex : -1, time : 3171},
            { locationIndex : -1, time : 3195},
            { locationIndex : -1, time : 3212},
            { locationIndex : -1, time : 3234},
            { locationIndex : -1, time : 3274},
            { locationIndex : -1, time : 3297},
            { locationIndex : -1, time : 3338},
            { locationIndex : -1, time : 3361},
            { locationIndex : -1, time : 3393},
            { locationIndex : -1, time : 3418},
            { locationIndex : -1, time : 3450},
            { locationIndex : -1, time : 3610},
            { locationIndex : -1, time : 3641},
            { locationIndex : -1, time : 3671},
            { locationIndex : -1, time : 3684}
        ]
    },
    {
        difficultyLabel : 'normal',
        difficultyLevel : 5,
        patterns : [
            { locationIndex : -1, time : 404   } ,
            { locationIndex : -1, time : 420   } ,
            { locationIndex : -1, time : 428   } ,
            { locationIndex : -1, time : 440   } ,
            { locationIndex : -1, time : 444   } ,
            { locationIndex : -1, time : 451   } ,
            { locationIndex : -1, time : 465   } ,
            { locationIndex : -1, time : 481   } ,
            { locationIndex : -1, time : 490   } ,
            { locationIndex : -1, time : 502   } ,
            { locationIndex : -1, time : 506   } ,
            { locationIndex : -1, time : 513   } ,
            { locationIndex : -1, time : 529   } ,
            { locationIndex : -1, time : 545   } ,
            { locationIndex : -1, time : 554   } ,
            { locationIndex : -1, time : 567   } ,
            { locationIndex : -1, time : 571   } ,
            { locationIndex : -1, time : 578   } ,
            { locationIndex : -1, time : 586   } ,
            { locationIndex : -1, time : 594   } ,
            { locationIndex : -1, time : 607   } ,
            { locationIndex : -1, time : 616   } ,
            { locationIndex : -1, time : 628   } ,
            { locationIndex : -1, time : 633   } ,
            { locationIndex : -1, time : 640   } ,
            { locationIndex : -1, time : 657   } ,
            { locationIndex : -1, time : 673   } ,
            { locationIndex : -1, time : 682   } ,
            { locationIndex : -1, time : 694   } ,
            { locationIndex : -1, time : 698   } ,
            { locationIndex : -1, time : 705   } ,
            { locationIndex : -1, time : 720   } ,
            { locationIndex : -1, time : 734   } ,
            { locationIndex : -1, time : 744   } ,
            { locationIndex : -1, time : 757   } ,
            { locationIndex : -1, time : 760   } ,
            { locationIndex : -1, time : 768   } ,
            { locationIndex : -1, time : 784   } ,
            { locationIndex : -1, time : 800   } ,
            { locationIndex : -1, time : 809   } ,
            { locationIndex : -1, time : 821   } ,
            { locationIndex : -1, time : 826   } ,
            { locationIndex : -1, time : 833   } ,
            { locationIndex : -1, time : 841   } ,
            { locationIndex : -1, time : 849   } ,
            { locationIndex : -1, time : 863   } ,
            { locationIndex : -1, time : 872   } ,
            { locationIndex : -1, time : 882   } ,
            { locationIndex : -1, time : 887   } ,
            { locationIndex : -1, time : 895   } ,
            { locationIndex : -1, time : 911   } ,
            { locationIndex : -1, time : 929   } ,
            { locationIndex : -1, time : 937   } ,
            { locationIndex : -1, time : 949   } ,
            { locationIndex : -1, time : 954   } ,
            { locationIndex : -1, time : 961   } ,
            { locationIndex : -1, time : 976   } ,
            { locationIndex : -1, time : 991   } ,
            { locationIndex : -1, time : 1000  } ,
            { locationIndex : -1, time : 1013  } ,
            { locationIndex : -1, time : 1017  } ,
            { locationIndex : -1, time : 1024  } ,
            { locationIndex : -1, time : 1040  } ,
            { locationIndex : -1, time : 1056  } ,
            { locationIndex : -1, time : 1064  } ,
            { locationIndex : -1, time : 1077  } ,
            { locationIndex : -1, time : 1082  } ,
            { locationIndex : -1, time : 1089  } ,
            { locationIndex : -1, time : 1103  } ,
            { locationIndex : -1, time : 1119  } ,
            { locationIndex : -1, time : 1127  } ,
            { locationIndex : -1, time : 1140  } ,
            { locationIndex : -1, time : 1144  } ,
            { locationIndex : -1, time : 1152  } ,
            { locationIndex : -1, time : 1167  } ,
            { locationIndex : -1, time : 1183  } ,
            { locationIndex : -1, time : 1193  } ,
            { locationIndex : -1, time : 1205  } ,
            { locationIndex : -1, time : 1209  } ,
            { locationIndex : -1, time : 1216  } ,
            { locationIndex : -1, time : 1224  } ,
            { locationIndex : -1, time : 1231  } ,
            { locationIndex : -1, time : 1246  } ,
            { locationIndex : -1, time : 1255  } ,
            { locationIndex : -1, time : 1267  } ,
            { locationIndex : -1, time : 1271  } ,
            { locationIndex : -1, time : 1279  } ,
            { locationIndex : -1, time : 1295  } ,
            { locationIndex : -1, time : 1310  } ,
            { locationIndex : -1, time : 1320  } ,
            { locationIndex : -1, time : 1333  } ,
            { locationIndex : -1, time : 1337  } ,
            { locationIndex : -1, time : 1343  } ,
            { locationIndex : -1, time : 1358  } ,
            { locationIndex : -1, time : 1374  } ,
            { locationIndex : -1, time : 1383  } ,
            { locationIndex : -1, time : 1394  } ,
            { locationIndex : -1, time : 1399  } ,
            { locationIndex : -1, time : 1406  } ,
            { locationIndex : -1, time : 1423  } ,
            { locationIndex : -1, time : 1440  } ,
            { locationIndex : -1, time : 1448  } ,
            { locationIndex : -1, time : 1471  } ,
            { locationIndex : -1, time : 1478  } ,
            { locationIndex : -1, time : 1486  } ,
            { locationIndex : -1, time : 1502  } ,
            { locationIndex : -1, time : 1510  } ,
            { locationIndex : -1, time : 1536  } ,
            { locationIndex : -1, time : 1543  } ,
            { locationIndex : -1, time : 1551  } ,
            { locationIndex : -1, time : 1567  } ,
            { locationIndex : -1, time : 1575  } ,
            { locationIndex : -1, time : 1599  } ,
            { locationIndex : -1, time : 1608  } ,
            { locationIndex : -1, time : 1615  } ,
            { locationIndex : -1, time : 1630  } ,
            { locationIndex : -1, time : 1639  } ,
            { locationIndex : -1, time : 1680  } ,
            { locationIndex : -1, time : 1695  } ,
            { locationIndex : -1, time : 1702  } ,
            { locationIndex : -1, time : 1718  } ,
            { locationIndex : -1, time : 1725  } ,
            { locationIndex : -1, time : 1734  } ,
            { locationIndex : -1, time : 1742  } ,
            { locationIndex : -1, time : 1757  } ,
            { locationIndex : -1, time : 1766  } ,
            { locationIndex : -1, time : 1791  } ,
            { locationIndex : -1, time : 1798  } ,
            { locationIndex : -1, time : 1806  } ,
            { locationIndex : -1, time : 1823  } ,
            { locationIndex : -1, time : 1830  } ,

            { locationIndex : -1, time : 1874  } ,
            { locationIndex : -1, time : 1889  } ,
            { locationIndex : -1, time : 1897  } ,
            { locationIndex : -1, time : 1938  } ,
            { locationIndex : -1, time : 1954  } ,
            { locationIndex : -1, time : 1954  } ,
            { locationIndex : -1, time : 1963  } ,
            { locationIndex : -1, time : 1975  } ,
            { locationIndex : -1, time : 1979  } ,
            { locationIndex : -1, time : 1986  } ,
            { locationIndex : -1, time : 1993  } ,
            { locationIndex : -1, time : 2000  } ,
            { locationIndex : -1, time : 2016  } ,
            { locationIndex : -1, time : 2024  } ,
            { locationIndex : -1, time : 2037  } ,
            { locationIndex : -1, time : 2041  } ,
            { locationIndex : -1, time : 2048  } ,
            { locationIndex : -1, time : 2066  } ,
            { locationIndex : -1, time : 2082  } ,
            { locationIndex : -1, time : 2089  } ,
            { locationIndex : -1, time : 2103  } ,
            { locationIndex : -1, time : 2106  } ,
            { locationIndex : -1, time : 2113  } ,
            { locationIndex : -1, time : 2128  } ,
            { locationIndex : -1, time : 2143  } ,
            { locationIndex : -1, time : 2152  } ,
            { locationIndex : -1, time : 2163  } ,
            { locationIndex : -1, time : 2167  } ,
            { locationIndex : -1, time : 2175  } ,
            { locationIndex : -1, time : 2192  } ,
            { locationIndex : -1, time : 2207  } ,
            { locationIndex : -1, time : 2217  } ,
            { locationIndex : -1, time : 2229  } ,
            { locationIndex : -1, time : 2233  } ,
            { locationIndex : -1, time : 2240  } ,
            { locationIndex : -1, time : 2248  } ,
            { locationIndex : -1, time : 2256  } ,
            { locationIndex : -1, time : 2271  } ,
            { locationIndex : -1, time : 2279  } ,
            { locationIndex : -1, time : 2292  } ,
            { locationIndex : -1, time : 2296  } ,
            { locationIndex : -1, time : 2304  } ,
            { locationIndex : -1, time : 2319  } ,
            { locationIndex : -1, time : 2335  } ,
            { locationIndex : -1, time : 2343  } ,
            { locationIndex : -1, time : 2357  } ,
            { locationIndex : -1, time : 2361  } ,
            { locationIndex : -1, time : 2368  } ,
            { locationIndex : -1, time : 2376  } ,
            { locationIndex : -1, time : 2383  } ,
            { locationIndex : -1, time : 2397  } ,
            { locationIndex : -1, time : 2407  } ,
            { locationIndex : -1, time : 2419  } ,
            { locationIndex : -1, time : 2423  } ,
            { locationIndex : -1, time : 2431  } ,
            { locationIndex : -1, time : 2447  } ,
            { locationIndex : -1, time : 2463  } ,
            { locationIndex : -1, time : 2471  } ,
            { locationIndex : -1, time : 2485  } ,
            { locationIndex : -1, time : 2489  } ,
            { locationIndex : -1, time : 2497  } ,
            { locationIndex : -1, time : 2505  } ,
            { locationIndex : -1, time : 2512  } ,
            { locationIndex : -1, time : 2520  } ,
            { locationIndex : -1, time : 2528  } ,
            { locationIndex : -1, time : 2535  } ,
            { locationIndex : -1, time : 2544  } ,
            { locationIndex : -1, time : 2551  } ,
            { locationIndex : -1, time : 2558  } ,
            { locationIndex : -1, time : 2567  } ,
            { locationIndex : -1, time : 2574  } ,
            { locationIndex : -1, time : 2589  } ,
            { locationIndex : -1, time : 2598  } ,
            { locationIndex : -1, time : 2611  } ,
            { locationIndex : -1, time : 2616  } ,
            { locationIndex : -1, time : 2622  } ,
            { locationIndex : -1, time : 2629  } ,
            { locationIndex : -1, time : 2637  } ,
            { locationIndex : -1, time : 2653  } ,
            { locationIndex : -1, time : 2662  } ,
            { locationIndex : -1, time : 2675  } ,
            { locationIndex : -1, time : 2678  } ,
            { locationIndex : -1, time : 2686  } ,
            { locationIndex : -1, time : 2695  } ,
            { locationIndex : -1, time : 2702  } ,
            { locationIndex : -1, time : 2710  } ,
            { locationIndex : -1, time : 2719  } ,
            { locationIndex : -1, time : 2728  } ,
            { locationIndex : -1, time : 2736  } ,
            { locationIndex : -1, time : 2743  } ,
            { locationIndex : -1, time : 2746  } ,
            { locationIndex : -1, time : 2751  } ,
            { locationIndex : -1, time : 2759  } ,
            { locationIndex : -1, time : 2766  } ,
            { locationIndex : -1, time : 2774  } ,
            { locationIndex : -1, time : 2782  } ,
            { locationIndex : -1, time : 2789  } ,
            { locationIndex : -1, time : 2798  } ,
            { locationIndex : -1, time : 2804  } ,
            { locationIndex : -1, time : 2808  } ,
            { locationIndex : -1, time : 2814  } ,
            { locationIndex : -1, time : 2820  } ,
            { locationIndex : -1, time : 2828  } ,
            { locationIndex : -1, time : 2837  } ,
            { locationIndex : -1, time : 2846  } ,
            { locationIndex : -1, time : 2854  } ,
            { locationIndex : -1, time : 2862  } ,
            { locationIndex : -1, time : 2870  } ,
            { locationIndex : -1, time : 2879  } ,
            { locationIndex : -1, time : 2886  } ,
            { locationIndex : -1, time : 2893  } ,
            { locationIndex : -1, time : 2907  } ,
            { locationIndex : -1, time : 2917  } ,
            { locationIndex : -1, time : 2926  } ,
            { locationIndex : -1, time : 2934  } ,
            { locationIndex : -1, time : 2936  } ,
            { locationIndex : -1, time : 2942  } ,
            { locationIndex : -1, time : 2950  } ,
            { locationIndex : -1, time : 2957  } ,
            { locationIndex : -1, time : 2974  } ,
            { locationIndex : -1, time : 2982  } ,
            { locationIndex : -1, time : 3014  } ,
            { locationIndex : -1, time : 3020  } ,
            { locationIndex : -1, time : 3037  } ,
            { locationIndex : -1, time : 3046  } ,
            { locationIndex : -1, time : 3078  } ,
            { locationIndex : -1, time : 3085  } ,
            { locationIndex : -1, time : 3101  } ,
            { locationIndex : -1, time : 3109  } ,
            { locationIndex : -1, time : 3143  } ,
            { locationIndex : -1, time : 3150  } ,
            { locationIndex : -1, time : 3164  } ,
            { locationIndex : -1, time : 3173  } ,
            { locationIndex : -1, time : 3189  } ,
            { locationIndex : -1, time : 3198  } ,
            { locationIndex : -1, time : 3231  } ,
            { locationIndex : -1, time : 3238  } ,
            { locationIndex : -1, time : 3269  } ,
            { locationIndex : -1, time : 3276  } ,
            { locationIndex : -1, time : 3293  } ,
            { locationIndex : -1, time : 3300  } ,
            { locationIndex : -1, time : 3332  } ,
            { locationIndex : -1, time : 3340  } ,
            { locationIndex : -1, time : 3348  } ,
            { locationIndex : -1, time : 3357  } ,
            { locationIndex : -1, time : 3364  } ,
            { locationIndex : -1, time : 3372  } ,
            { locationIndex : -1, time : 3380  } ,
            { locationIndex : -1, time : 3388  } ,
            { locationIndex : -1, time : 3396  } ,
            { locationIndex : -1, time : 3404  } ,
            { locationIndex : -1, time : 3417  } ,
            { locationIndex : -1, time : 3427  } ,
            { locationIndex : -1, time : 3435  } ,
            { locationIndex : -1, time : 3442  } ,
            { locationIndex : -1, time : 3451  } ,
            { locationIndex : -1, time : 3532  } ,
            { locationIndex : -1, time : 3581  } ,
            { locationIndex : -1, time : 3637  } ,
            { locationIndex : -1, time : 3640  } ,
            { locationIndex : -1, time : 3660  } ,
            { locationIndex : -1, time : 3676  } ,
            { locationIndex : -1, time : 3684  }
        ]
    }
]

addShuttingStarSong(song);

song = {};
song.name = '큰집 18층으로 떠나는 여행';
song.composer = '우아한형제들';
song.noteWriter = 'HJOW';
song.bgaUrl = '';
song.musicUrl = './resources/songs/woowahan/track07.mp3';
song.thumbnailUrl = '';
song.description = `
|Music: 우아한형제들
|  https://www.woowahan.com/music
|License: 
|  https://www.woowahan.com/music/license
`;
song.loadingTime = 10;
song.bpm = 120;
song.endTime = 4350;
song.timeConstant = -337;
song.timeMultiplier = 1;
song.serial = 'nai4ilaHbwgwgnoimomwenofnJ93f8gp34qgD39p4g';
song.test = true; // 테스트 이후 false 로 변경
song.difficulties = [
    {
        difficultyLabel : 'hard',
        difficultyLevel : 7,
        patterns : [
            
        ]
    }
]

addShuttingStarSong(song);